name: help_me
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+8
  geolocator: ^5.1.5
  provider: ^4.3.1
  http: ^0.12.1
  flutter_spinkit: "^4.1.2"
  flutter_icons: ^1.1.0
  flutter_svg: ^0.18.0
  freezed_annotation: ^0.7.1
  flutter_bloc: ^4.0.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  #cloud_firestore: ^0.14.1+3
  get_it: ^4.0.2
  injectable: ^0.3.0
  flushbar: ^1.10.0
  uuid: ^2.0.4
  dartz: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter  
  build_runner:
  freezed: ^0.10.7
  lint: ^1.1.1
  injectable_generator: ^0.3.5

flutter:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSansBlack.ttf
          weight: 600
        - asset: assets/fonts/ProductSansRegular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true

