name: help_me
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+8
  geolocator: ^5.1.5
  provider: ^3.0.0
  http: ^0.12.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_spinkit: "^4.1.2"
  flutter_icons: ^1.1.0
  google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSansBlack.ttf
          weight: 600
        - asset: assets/fonts/ProductSansRegular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf   
          weight: 700 


  assets:
    - assets/images/
  uses-material-design: true
