name: help_me
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  cupertino_icons: ^0.1.2
  dartz: ^0.9.0
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  flushbar: ^1.10.0
  flutter_bloc: ^4.0.0
  flutter_svg: ^0.18.0
  freezed_annotation: ^0.7.1
  geolocator: ^5.1.5
  get_it: ^4.0.2
  google_maps_flutter: ^0.5.21+8
  google_sign_in: ^4.4.4
  http: ^0.12.1
  injectable: ^0.3.0
  json_annotation: ^3.1.0
  kt_dart: ^0.8.0
  provider: ^4.3.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  auto_route_generator: ^0.6.10
  freezed: ^0.10.7
  injectable_generator: ^0.3.5
  json_serializable: ^3.5.0
  lint: ^1.1.1

dependency_overrides:
  analyzer: '0.40.2'
  meta: '1.2.3'

flutter:
  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
